name: sem-leh
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - pytorch
  - pytorch-cuda=12.4
  - pip
  - python=3.9
  - torchvision
  - torchaudio
  - pip:
      - git+https://github.com/philheller/transformers.git
      # - -e ../transformers
